import { Inter, Roboto_Flex } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
const roboto_flex= Roboto_Flex({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={roboto_flex.className}>{children}</body>
      </html>
    </ClerkProvider>
    
  );
}
